"use client";

import { Button, Card, Chip, Spinner, TextArea } from "@heroui/react";
import { type ChangeEvent, type FormEvent, useRef, useState } from "react";
import type { AgentDecision, DiagnosticSession } from "@/lib/diagnostics/types";

type Language = "en" | "fr" | "bm" | "zh";
type Provider = "deepseek" | "openrouter" | "safe-fallback";
type Recognition = {
  lang: string; interimResults: boolean; continuous: boolean; start: () => void; stop: () => void;
  onresult: ((event: { resultIndex: number; results: { length: number; [index: number]: { [index: number]: { transcript: string } } } }) => void) | null;
  onerror: (() => void) | null; onend: (() => void) | null;
};
type RecognitionConstructor = new () => Recognition;
type ResponsePayload = { session: DiagnosticSession; decision: AgentDecision; provider: Provider };

type Labels = Record<
  "subtitle" | "ready" | "new" | "next" | "start" | "first" | "why" | "power" | "input" | "question" | "placeholder" | "speak" | "stop" | "photo" | "attached" | "remove" | "demo" | "analyze" | "analyzing" | "response" | "read" | "machine" | "manufacturer" | "model" | "status" | "unknown" | "hypotheses" | "noHypotheses" | "safety" | "noSafety" | "observations" | "noObservations" | "evidence" | "noEvidence" | "voiceUnavailable" | "voiceFailed" | "imageInvalid" | "imageLarge" | "imageFailed" | "requestFailed" | "imageOnly", string>;

const t: Record<Language, Labels> = {
  en: { subtitle: "A guided diagnostic workspace that preserves context and recommends one safe, useful test at a time.", ready: "Ready for a new session", new: "New session", next: "01 · Next action", start: "Describe the problem to begin", first: "Start with the exact machine model, symptoms, error code, and what you can physically observe.", why: "Why this test", power: "Safety: turn off and unplug the machine before performing this test.", input: "02 · Technician input", question: "What happened during the test?", placeholder: "Example: The sensor lever returns freely, but the paper still stops before printing.", speak: "Speak observation", stop: "Stop listening", photo: "Attach inspection photo", attached: "Photo attached", remove: "Remove", demo: "Load Epson demo example", analyze: "Get next test", analyzing: "Analyzing…", response: "03 · Agent response", read: "Read aloud", machine: "Machine", manufacturer: "Manufacturer", model: "Model", status: "Status", unknown: "Not identified", hypotheses: "Hypotheses", noHypotheses: "No hypothesis has been formed yet.", safety: "Safety", noSafety: "No additional safety warning for the current step.", observations: "Recent observations", noObservations: "Observations will appear here after the first message.", evidence: "Technical evidence", noEvidence: "Sources appear when a model or error code needs technical evidence.", voiceUnavailable: "Voice input is not supported by this browser. Use Chrome or type the observation.", voiceFailed: "Voice input could not be transcribed. Try again or type the observation.", imageInvalid: "Choose a JPEG, PNG, WebP, or GIF image.", imageLarge: "Choose an image smaller than 5 MB.", imageFailed: "The selected image could not be read.", requestFailed: "The diagnostic request failed.", imageOnly: "Please analyze the attached image." },
  fr: { subtitle: "Un espace de diagnostic guidé qui conserve le contexte et propose un test sûr et utile à la fois.", ready: "Prêt pour une nouvelle session", new: "Nouvelle session", next: "01 · Prochaine action", start: "Décris le problème pour commencer", first: "Commence par le modèle exact, les symptômes, le code d’erreur et ce que tu peux observer physiquement.", why: "Pourquoi ce test", power: "Sécurité : éteins et débranche la machine avant ce test.", input: "02 · Saisie du technicien", question: "Que s’est-il passé pendant le test ?", placeholder: "Exemple : Le levier du capteur revient librement, mais le papier s’arrête avant l’impression.", speak: "Dicter l’observation", stop: "Arrêter l’écoute", photo: "Joindre une photo", attached: "Photo jointe", remove: "Retirer", demo: "Charger l’exemple Epson", analyze: "Obtenir le prochain test", analyzing: "Analyse en cours…", response: "03 · Réponse de l’agent", read: "Lire à voix haute", machine: "Machine", manufacturer: "Fabricant", model: "Modèle", status: "État", unknown: "Non identifié", hypotheses: "Hypothèses", noHypotheses: "Aucune hypothèse n’a encore été formulée.", safety: "Sécurité", noSafety: "Aucun avertissement supplémentaire pour cette étape.", observations: "Observations récentes", noObservations: "Les observations apparaîtront ici après le premier message.", evidence: "Sources techniques", noEvidence: "Les sources apparaissent lorsqu’un modèle ou un code d’erreur demande une vérification technique.", voiceUnavailable: "La saisie vocale n’est pas prise en charge par ce navigateur. Utilise Chrome ou écris l’observation.", voiceFailed: "La voix n’a pas pu être transcrite. Réessaie ou écris l’observation.", imageInvalid: "Choisis une image JPEG, PNG, WebP ou GIF.", imageLarge: "Choisis une image de moins de 5 Mo.", imageFailed: "La photo sélectionnée n’a pas pu être lue.", requestFailed: "La demande de diagnostic a échoué.", imageOnly: "Analyse la photo jointe." },
  bm: { subtitle: "A ye dɔnkili ka ɲɛnabɔ, a bɛ ko bɛɛ mara, ka kɛcogo kelen-kelen di min bɛ kisɛ ka ɲi.", ready: "Sɛgɛsɛgɛli kura bɛ se ka daminɛ", new: "Sɛgɛsɛgɛli kura", next: "01 · Kɛcogo nata", start: "Gɛlɛnko fɔ ka daminɛ", first: "Fɔ masinɲɛ sɔrɔ, a modele, gɛlɛnko, erreur code ani fɛn min i bɛ se ka ye.", why: "Mun na test in", power: "Kisɛ : masinɲɛ dɔgɔya ani a jɔ yen ka fɔlɔ test in ɲɛ.", input: "02 · Baara kɛla ka donni", question: "Mun kɛra test waati ?", placeholder: "Misali : Capteur lever bɛ segin ɲuman, nka papier bɛ jɔ print ɲɛ.", speak: "Yeeliya fɔ", stop: "Tulon", photo: "Ɲɛsinni foto fara", attached: "Foto bɛ yen", remove: "Bɔ yen", demo: "Epson misali don", analyze: "Test nata sɔrɔ", analyzing: "A bɛ sɛgɛsɛgɛ…", response: "03 · Agent jaabi", read: "A kalan ka fɔ", machine: "Masinɲɛ", manufacturer: "Masin kɛla", model: "Modele", status: "Cogo", unknown: "A ma dɔnkili", hypotheses: "Miiri", noHypotheses: "Miiri si ma da fɔlɔ.", safety: "Kisɛ", noSafety: "Kisɛ fɔli kura tɛ nin cogo la.", observations: "Yeeliya kɔrɔbɔ", noObservations: "Yeeliya bɛna bɔ yan message fɔlɔ kɔ.", evidence: "Tekiniki sebɛn", noEvidence: "Sebɛn bɛna bɔ ni modele walima erreur code ka nafa bɛ a la.", voiceUnavailable: "Nin navigateur tɛ se ka yeeliya minɛ. Chrome walima sɛbɛnni kɛ.", voiceFailed: "Yeeliya ma se ka bɔ sɛbɛn na. A segin walima sɛbɛnni kɛ.", imageInvalid: "JPEG, PNG, WebP walima GIF foto sugandi.", imageLarge: "Foto min ka dɔgɔ 5 Mo kɔrɔ sugandi.", imageFailed: "Foto sugandilen ma se ka kalan.", requestFailed: "Sɛgɛsɛgɛli ɲininkali ma kɛ.", imageOnly: "Foto fara sɛgɛsɛgɛ." },
  zh: { subtitle: "一个保留诊断上下文的引导式工作区，每次只建议一个安全且有用的测试。", ready: "可开始新会话", new: "新建会话", next: "01 · 下一步操作", start: "描述问题以开始", first: "请先提供准确型号、症状、错误代码以及你能直接观察到的现象。", why: "为什么进行此测试", power: "安全提示：进行此测试前请关闭并拔掉设备电源。", input: "02 · 技术员输入", question: "测试过程中发生了什么？", placeholder: "示例：传感器拨杆能自由回位，但纸张仍在打印前停止。", speak: "语音输入", stop: "停止聆听", photo: "添加检查照片", attached: "已添加照片", remove: "移除", demo: "加载 Epson 演示示例", analyze: "获取下一项测试", analyzing: "正在分析…", response: "03 · 智能助手回复", read: "朗读", machine: "设备", manufacturer: "制造商", model: "型号", status: "状态", unknown: "未识别", hypotheses: "假设", noHypotheses: "尚未形成假设。", safety: "安全", noSafety: "当前步骤没有额外安全警告。", observations: "最近观察", noObservations: "第一条消息发送后，观察记录会显示在这里。", evidence: "技术依据", noEvidence: "当型号或错误代码需要技术依据时，来源会显示在这里。", voiceUnavailable: "此浏览器不支持语音输入。请使用 Chrome 或直接输入观察结果。", voiceFailed: "无法转录语音。请重试或直接输入观察结果。", imageInvalid: "请选择 JPEG、PNG、WebP 或 GIF 图片。", imageLarge: "请选择小于 5 MB 的图片。", imageFailed: "无法读取所选图片。", requestFailed: "诊断请求失败。", imageOnly: "请分析所附图片。" },
};

const speechLocale: Record<Language, string> = { en: "en-US", fr: "fr-FR", bm: "bm-ML", zh: "zh-CN" };
const examples: Record<Language, string> = { en: "The Epson L3210 feeds paper, but it reports a paper jam before printing starts.", fr: "L’Epson L3210 entraîne le papier, mais signale un bourrage avant le début de l’impression.", bm: "Epson L3210 bɛ papier minɛ, nka a bɛ papier jam fɔ print ka daminɛ ɲɛ.", zh: "Epson L3210 能进纸，但在开始打印前提示卡纸。" };
const localized: Record<Language, Record<string, string>> = { en: { active: "Active", resolved: "Resolved", escalated: "Escalated", low: "low", medium: "medium", high: "high", technician: "technician", agent: "agent", vision: "vision" }, fr: { active: "Actif", resolved: "Résolu", escalated: "À escalader", low: "faible", medium: "moyen", high: "élevé", technician: "technicien", agent: "agent", vision: "vision" }, bm: { active: "Bɛ baara kɛ", resolved: "A ban", escalated: "A ka taa ɲɛnamaya kɛla ma", low: "dɔgɔ", medium: "cɛma", high: "belebele", technician: "baara kɛla", agent: "agent", vision: "nyɛ" }, zh: { active: "进行中", resolved: "已解决", escalated: "需升级处理", low: "低", medium: "中", high: "高", technician: "技术员", agent: "助手", vision: "视觉" } };
const label = (value: string, language: Language) => localized[language][value] ?? value;

export function WorkshopDashboard() {
  const [language, setLanguage] = useState<Language>("fr"); const [message, setMessage] = useState(""); const [image, setImage] = useState<string>(); const [imageName, setImageName] = useState<string>();
  const [sessionId, setSessionId] = useState<string | undefined>(() => typeof window === "undefined" ? undefined : window.localStorage.getItem("workshop-master-session") ?? undefined);
  const [session, setSession] = useState<DiagnosticSession>(); const [decision, setDecision] = useState<AgentDecision>(); const [provider, setProvider] = useState<Provider>(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false); const [listening, setListening] = useState(false);
  const recognition = useRef<Recognition | null>(null); const copy = t[language]; const test = session?.currentTest;

  function voice() {
    if (listening) { recognition.current?.stop(); return; }
    const browser = window as Window & typeof globalThis & { SpeechRecognition?: RecognitionConstructor; webkitSpeechRecognition?: RecognitionConstructor }; const Constructor = browser.SpeechRecognition ?? browser.webkitSpeechRecognition;
    if (!Constructor) { setError(copy.voiceUnavailable); return; }
    const instance = new Constructor(); instance.lang = speechLocale[language]; instance.interimResults = false; instance.continuous = false;
    instance.onresult = (event) => setMessage((value) => `${value} ${Array.from({ length: event.results.length - event.resultIndex }, (_, i) => event.results[event.resultIndex + i][0].transcript).join(" ")}`.trim());
    instance.onerror = () => setError(copy.voiceFailed); instance.onend = () => setListening(false); recognition.current = instance; setError(undefined); setListening(true); instance.start();
  }
  function speak() { if (!decision || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(decision.assistantMessage); utterance.lang = speechLocale[language]; window.speechSynthesis.speak(utterance); }
  function chooseImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.match(/^image\/(jpeg|png|webp|gif)$/)) { setError(copy.imageInvalid); return; } if (file.size > 5 * 1024 * 1024) { setError(copy.imageLarge); return; } const reader = new FileReader(); reader.onload = () => { setImage(reader.result as string); setImageName(file.name); setError(undefined); }; reader.onerror = () => setError(copy.imageFailed); reader.readAsDataURL(file); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const text = message.trim() || (image ? copy.imageOnly : ""); if (!text || busy) return; setBusy(true); setError(undefined); try { const response = await fetch("/api/diagnostics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text, sessionId, imageDataUrl: image, language }) }); const result = await response.json() as ResponsePayload | { error: string }; if (!response.ok || !("session" in result)) throw new Error("error" in result ? result.error : copy.requestFailed); setSession(result.session); setDecision(result.decision); setProvider(result.provider); setSessionId(result.session.id); window.localStorage.setItem("workshop-master-session", result.session.id); setMessage(""); setImage(undefined); setImageName(undefined); } catch (caught) { setError(caught instanceof Error ? caught.message : copy.requestFailed); } finally { setBusy(false); } }
  function reset() { window.localStorage.removeItem("workshop-master-session"); setSessionId(undefined); setSession(undefined); setDecision(undefined); setProvider(undefined); setMessage(""); setImage(undefined); setImageName(undefined); setError(undefined); }

  return <main className="min-h-screen overflow-hidden bg-[#07111f] text-slate-100"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_15%_0%,rgba(8,145,178,0.2),transparent_31%),radial-gradient(circle_at_90%_20%,rgba(37,99,235,0.15),transparent_25%)]" /><div className="relative mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <header className="mb-6 flex flex-col justify-between gap-4 border-b border-slate-800/80 pb-6 sm:flex-row sm:items-end"><div><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl border border-cyan-300/20 bg-cyan-300/10 text-xl">🔧</div><div><p className="text-xs font-semibold tracking-[0.22em] text-cyan-300 uppercase">Workshop diagnostic system</p><h1 className="mt-1 text-2xl font-semibold text-white sm:text-3xl">The Workshop Master</h1></div></div><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-400">{copy.subtitle}</p></div><div className="flex flex-wrap items-center gap-3"><Chip color="success" variant="soft">{session ? `${label(session.status, language)}` : copy.ready}</Chip>{session && <Button variant="tertiary" size="sm" onPress={reset}>{copy.new}</Button>}</div></header>
    <section className="grid gap-6 lg:grid-cols-[minmax(0,1.65fr)_minmax(280px,.85fr)]"><div className="space-y-6">
      <Card variant="secondary" className="border border-cyan-400/15 bg-slate-900/80 p-5 shadow-2xl shadow-black/20 sm:p-6"><Card.Header className="flex items-start justify-between gap-3 p-0"><div><p className="text-xs font-semibold tracking-[.18em] text-cyan-300 uppercase">{copy.next}</p><Card.Title className="mt-1 text-xl text-white">{test?.title ?? copy.start}</Card.Title></div>{test && <Chip color={test.risk === "low" ? "success" : "warning"} variant="soft">{label(test.risk, language)}</Chip>}</Card.Header><Card.Content className="p-0"><p className="mt-4 leading-7 text-slate-100">{test?.instruction ?? copy.first}</p>{test?.purpose && <p className="mt-3 border-l-2 border-slate-700 pl-3 text-sm text-slate-400">{copy.why}: {test.purpose}</p>}{test?.requiresPowerOff && <p className="mt-4 rounded-lg border border-amber-400/20 bg-amber-400/10 p-3 text-sm text-amber-100">{copy.power}</p>}</Card.Content></Card>
      <Card variant="secondary" className="border border-slate-700/70 bg-slate-900/70 p-5 sm:p-6"><Card.Header className="flex items-start justify-between gap-3 p-0"><div><p className="text-xs font-semibold tracking-[.18em] text-cyan-300 uppercase">{copy.input}</p><Card.Title className="mt-1 text-xl text-white">{copy.question}</Card.Title></div><div className="flex items-center gap-2"><select aria-label="Language" value={language} onChange={(event) => setLanguage(event.target.value as Language)} className="rounded-lg border border-slate-700 bg-slate-950 px-2.5 py-1.5 text-xs text-slate-300"><option value="fr">Français</option><option value="en">English</option><option value="zh">中文</option><option value="bm">Bamanankan · beta</option></select>{provider && <Chip variant="soft" size="sm" className="hidden sm:inline-flex">{provider}</Chip>}</div></Card.Header><Card.Content className="p-0"><form className="mt-5" onSubmit={submit}><TextArea aria-label={copy.question} value={message} onChange={(event) => setMessage(event.target.value)} placeholder={copy.placeholder} disabled={busy} className="min-h-36 border border-slate-700 bg-slate-950/90 px-4 py-3 text-white placeholder:text-slate-600" /><div className="mt-3 flex flex-wrap items-center gap-3"><Button variant="secondary" size="sm" type="button" onPress={voice} isDisabled={busy}>{listening ? `■ ${copy.stop}` : `◉ ${copy.speak}`}</Button><label className="cursor-pointer rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:border-cyan-400">+ {copy.photo}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy} onChange={chooseImage} /></label>{imageName && <span className="text-sm text-cyan-100">{copy.attached}: {imageName} <button className="ml-2 underline" type="button" onClick={() => { setImage(undefined); setImageName(undefined); }}>{copy.remove}</button></span>}</div>{error && <p className="mt-3 rounded-lg border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}<div className="mt-4 flex flex-col justify-between gap-3 sm:flex-row"><Button variant="tertiary" size="sm" type="button" onPress={() => setMessage(examples[language])}>{copy.demo}</Button><Button variant="primary" type="submit" isDisabled={busy || (!message.trim() && !image)}>{busy ? <><Spinner size="sm" /> {copy.analyzing}</> : `${copy.analyze} →`}</Button></div></form></Card.Content></Card>
      {decision && <Card variant="secondary" className="border border-indigo-400/15 bg-indigo-950/20 p-5 sm:p-6"><Card.Header className="flex justify-between p-0"><p className="text-xs font-semibold tracking-[.18em] text-indigo-200 uppercase">{copy.response}</p><Button variant="tertiary" size="sm" onPress={speak}>◉ {copy.read}</Button></Card.Header><Card.Content className="p-0"><p className="mt-3 whitespace-pre-wrap leading-7 text-slate-200">{decision.assistantMessage}</p></Card.Content></Card>}
    </div><aside className="space-y-5"><Panel title={copy.machine}><dl className="space-y-3 text-sm"><Row label={copy.manufacturer} value={session?.machine.manufacturer || copy.unknown} /><Row label={copy.model} value={session?.machine.model || copy.unknown} /><Row label={copy.status} value={session ? label(session.status, language) : copy.unknown} /></dl></Panel><Panel title={copy.hypotheses}>{session?.hypotheses.length ? <ul className="space-y-3">{session.hypotheses.map((item) => <li key={item.id} className="border-l-2 border-slate-700 pl-3"><p className="text-sm text-slate-200">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.rationale}</p></li>)}</ul> : <Empty>{copy.noHypotheses}</Empty>}</Panel><Panel title={copy.safety} amber>{session?.safetyWarnings.length ? <ul className="space-y-2 text-sm text-amber-100">{session.safetyWarnings.map((item) => <li key={item}>• {item}</li>)}</ul> : <Empty>{copy.noSafety}</Empty>}</Panel><Panel title={copy.observations}>{session?.observations.length ? <ul className="space-y-3">{[...session.observations].slice(-5).reverse().map((item) => <li key={item.id} className="text-sm leading-6 text-slate-400"><span className="mr-2 text-xs uppercase text-slate-500">{label(item.source, language)}</span>{item.text}</li>)}</ul> : <Empty>{copy.noObservations}</Empty>}</Panel><Panel title={copy.evidence}>{session?.retrievedSources?.length ? <ul className="space-y-3">{session.retrievedSources.map((source) => <li key={source.url} className="text-sm text-slate-400"><a className="text-cyan-200 underline" href={source.url} target="_blank" rel="noreferrer">{source.title}</a></li>)}</ul> : <Empty>{copy.noEvidence}</Empty>}</Panel></aside></section>
  </div></main>;
}

function Panel({ title, amber, children }: { title: string; amber?: boolean; children: React.ReactNode }) { return <Card variant="secondary" className="border border-slate-700/60 bg-slate-900/65 p-5"><Card.Header className="p-0"><p className={`text-xs font-semibold tracking-[.18em] uppercase ${amber ? "text-amber-200" : "text-cyan-300"}`}>{title}</p></Card.Header><Card.Content className="mt-4 p-0">{children}</Card.Content></Card>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><dt className="text-slate-500">{label}</dt><dd className="text-right text-slate-200">{value}</dd></div>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="text-sm leading-6 text-slate-500">{children}</p>; }
